### ISSUE TITLE
Inline svg boolean does not work

### ISSUE THREAD

**Issue by roshecode** [romanVia/easy-frontend#1]
When `inlineSvg` option is `false` the build system calls `build:svg` task but it does not have.

**Comment by ma1oy** [comment]
This option had deleted in v1.1.0. Now you can turn on / off inline `svg` building into `prj.mcb.svg`.

**Comment by roshecode** [comment]
This option had deleted in v1.1.0. Now you can turn on / off inline svg building into prj.mcb.svg.
